FROM php:fpm
RUN apt-get update -y \
  && apt-get install -y openssl zip unzip zlib1g-dev libzip-dev libpng-dev libsodium-dev
RUN cd /tmp \
  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
  && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
  && php -r "unlink('composer-setup.php');" \
  && docker-php-ext-install -j$(nproc) gd bcmath sodium zip pdo_mysql
# COPY . $PWD
# RUN composer install
# RUN echo \
#   && php artisan install --db-host="db" --db-name="akaunting" --db-username="akaunting" --db-password="akaunting" --admin-email="admin@foo.bar" --admin-password="admin" \
#   && php artisan sample-data:seed
